config/routes.rb
Rails.application.routes.draw do
  resources :exchanges, only: [:show, :create]
  get '/listings/new_road', to: 'listings#new_road', as: 'newroad'
  get '/listings/new_mountain', to: 'listings#new_mountain', as: 'newmountain'
  get '/listings/:id/edit_road', to: 'listings#edit_road', as: 'editroad'
  get '/listings/:id/edit_mountain', to: 'listings#edit_mountain', as: 'editmountain'
  post '/exchanges/:id', to: 'exchanges#add_like'
  resources :listings, only: [:create, :show, :update] do 
    resources :comments
  end
  resources :products, only: [:show] do
    resources :reviews
  end
  get '/', to: 'products#index', as: 'home'
  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/users/:id/add', to: 'users#add', as: 'addmoney'
  post '/users/:id', to: 'users#add_money'
  post '/login', to: 'sessions#create'
  match '/logout', to: 'sessions#destroy', via: :delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :product
  belongs_to :user, optional: true
  has_one :exchange
  has_many :comments

  validates :price, presence: true

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end

  def display_price
    '%.2f' % self.price
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    def new_road
        @listing = Listing.new
    end

    def new_mountain
        @listing = Listing.new
    end

    def create
        @listing = Listing.create(listing_params)
        redirect_to listing_path(@listing)
    end

    def show
        @listing = Listing.find(params[:id])
        @comment = Comment.new
        @comment.listing_id = @listing.id
    end

    def edit_road
        @listing = Listing.find(params[:id])
    end

    def edit_mountain
        @listing = Listing.find(params[:id])
    end

    def update
        @listing = Listing.find(params[:id])
        @listing.update(listing_params)

        #send a flash notice on the page
        flash[:notice] = "Listing Updated!"

        redirect_to listing_path(@listing)
    end

    private

    def listing_params
        params.require(:listing).permit(:user_id, :product_id, :condition, :make, :size, :active, :price, :description)
    end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form_mountain.html.erb
<div class="container">
<%= form_for @listing do |form| %>
  <%= form.label "Product: " %>
  <%= form.collection_select :product_id, Product.where(:type_id => 2), :id, :name  %>
    <br><br>
  <%= form.label "Condition: " %>
  <%= form.select :condition, ['new', 'used']%>
    <br><br>
  <%= form.label "Make: " %>
  <%= form.select :make, ['Cannondale', 'Trek', 'Scott', 'BMC']%>
    <br><br>
  <%= form.label "Size: " %>
  <%= form.select :size, ['13cm', '14cm', '15cm', '16cm', '17cm', '18cm', '19cm','20cm','21cm','22cm','23cm']%>
    <br><br>
  <%= form.label "Price: "%>
  <%= form.number_field :price, step: "0.01" %>
    <br><br>
  <%= form.label "Post a description:" %>
  <%= form.text_area :description %>
    <br><br>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit "Submit" %>
<% end %>
</div>

app/views/listings/_form_road.html.erb
<div class="container">
<%= form_for @listing do |form| %>
  <%= form.label "Product: " %>
  <%= form.collection_select :product_id, Product.where(:type_id => 2), :id, :name  %>
    <br><br>
  <%= form.label "Condition: " %>
  <%= form.select :condition, ['new', 'used']%>
    <br><br>
  <%= form.label "Make: " %>
  <%= form.select :make, ['Cervelo', 'Trek', 'Scott', 'BMC']%>
    <br><br>
  <%= form.label "Size: " %>
  <%= form.select :size, ['46cm', '47cm', '48cm', '49cm', '50cm', '51cm', '52cm','53cm','54cm','55cm','56cm','57cm','58cm','59cm','60cm']%>
    <br><br>
  <%= form.label "Price: "%>
  <%= form.number_field :price, step: "0.01" %>
    <br><br>
  <%= form.label "Post a description:" %>
  <%= form.text_area :description %>
    <br><br>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.submit "Submit" %>
<% end %>
</div>

app/views/listings/edit_mountain.html.erb
<div class="container">
<h1>Edit your Mountain Bike listing</h1> <br>

<%= render partial: 'form_mountain' %>
</div>

app/views/listings/edit_road.html.erb
<div class="container">
<h1>Edit your Road Bike listing</h1> <br>

<%= render partial: 'form_road' %>
</div>

app/views/listings/new_mountain.html.erb
<div class="container">
<h1>Create a Mountain Bike Listing </h1> <br>

<%= render partial: 'form_mountain' %>
</div>

app/views/listings/new_road.html.erb
<div class="container">
<h1>Create a Road Bike Listing </h1> <br>

<%= render partial: 'form_road' %>
</div>

app/views/listings/show.html.erb
<div class="container">
#this is just a testing for future use.
<h1> <%= link_to "#{@listing.product.name} [#{@listing.product.model}]", product_path(@listing.product) %> </h1>

<%# flash notice when updated form is sent %>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<h3> Seller: <%= @listing.user.full_name %> <%="(#{@listing.user.approval_rating})"%> </h3> 

<%# ability for Seller to edit listing order %>
<% if @listing.user_id == current_user.id %>
        <% if @listing.product.type_id == 1 %>
            <%= link_to "Edit my Road Bike listing", editroad_path(@listing) %>
        <% else %> 
            <%= link_to "Edit my Mountain Bike listing", editmountain_path(@listing) %>
        <% end %>
<% end %>
    <br><br>



<div class="row">
    <div class="col-sm-4 my-auto">
        <h4> Price: $<%= @listing.display_price %> </h4> 
        <h4> Condition: <%= @listing.condition %> </h4>
        <h4> Make: <%= @listing.make %> </h4>
        <h4> Size: <%= @listing.size %> </h4>
    </div>
    <div class="col-sm-8 my-auto">
        <%= image_tag(@listing.product.image) %>
    </div>
</div>


<%= form_with scope: :exchange, url: exchanges_path do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.hidden_field :listing_id, value: @listing.id%>
    <% if @listing.active == false %>
        <h2>SOLD</h2>
    <% elsif @listing.user.id != current_user.id %>
        <% if current_user.balance < @listing.price %>
            <h3>You don't have enough money to buy this Bike, maybe next time!</h3>
            <h3><%= link_to "Click here to add more money", addmoney_path %></h3>
        <% else %>
            <%= f.submit "Buy Now" %>
        <% end %>
    <% end %>
<% end %>


<br><br>

<%= render partial: 'comments/form' %>

<br><br>

<div class="row">
    <div class="col my-auto">
        <h2>Comments (<%= @listing.comments.size %>) </h2>

        <% @listing.comments.each do |comment| %>
            <h5> <%= comment.user.first_name %> <%= comment.display_timestamp %> </h5>
            <%= comment.content %>
                <br><br>
        <% end %>
    </div>
</div>

</div>