config/routes.rb
Rails.application.routes.draw do
  resources :exchanges, only: [:show, :create]
  get '/listings/new_road', to: 'listings#new_road', as: 'newroad'
  get '/listings/new_mountain', to: 'listings#new_mountain', as: 'newmountain'
  get '/listings/:id/edit_road', to: 'listings#edit_road', as: 'editroad'
  get '/listings/:id/edit_mountain', to: 'listings#edit_mountain', as: 'editmountain'
  post '/exchanges/:id', to: 'exchanges#add_like'
  resources :listings, only: [:create, :show, :update] do 
    resources :comments
  end
  resources :products, only: [:show] do
    resources :reviews
  end
  get '/', to: 'products#index', as: 'home'
  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/users/:id/add', to: 'users#add', as: 'addmoney'
  post '/users/:id', to: 'users#add_money'
  post '/login', to: 'sessions#create'
  match '/logout', to: 'sessions#destroy', via: :delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :listings
    has_many :products, through: :listings
    has_many :reviews
    has_many :comments
    has_many :exchanges
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :username, presence: true
    # validates :username, uniqueness: true
    validates :username, length: {minimum: 4}
    validates :balance, presence: true

    has_secure_password


    def full_name
        self.first_name + " " + self.last_name
    end

    def active_listings
        self.listings.select {|listing| listing.active == true}
    end

    def inactive_listings
        self.listings.select {|listing| listing.active == false}
    end

    def sales
        self.inactive_listings.map {|listing| listing.exchange}
    end

    def purchases
        self.exchanges
    end

    def total_purchases
        purchases.size
    end 

    def total_sales
        sales.size
    end

    def total_exchanges
        total_purchases + total_sales
    end

    def display_likes
        current_likes = self.likes
        myexchanges = self.exchanges.size + self.inactive_listings.size

        if current_likes >= myexchanges
            current_likes = myexchanges
            self.save
        else  
            current_likes = self.likes
        end
        current_likes
    end

    def approval_rating
        mylikes = self.display_likes.to_f
        myexchanges = self.exchanges.size.to_f + self.inactive_listings.size.to_f
        approvalpercent = ""

        if mylikes == 0 || myexchanges == 0 
            approvalpercent = "0%"
        else 
            approvalrating = (mylikes.to_f / myexchanges.to_f) * 100
            approvalpercent = "#{approvalrating.to_i}%"
        end
        approvalpercent
    end

    def display_balance
        '%.2f' % self.balance
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :require_login, only: [:show, :add, :edit]

    def new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
          flash[:notice] = "Created a new account!"
          redirect_to home_path
        else
          flash[:alert] = @user.errors.full_messages
          redirect_to new_user_path
        end
    end

    def show
      # @user = User.find(params[:id])
      @user = User.find_by(id: session[:user_id])
    end

    def add
      @user = User.find_by(id: session[:user_id])
    end

    def add_money
      @user = User.find_by(id: session[:user_id])

      if !params[:user][:amount].empty?
        @user.balance += params[:user][:amount].to_f
        @user.save
        flash[:notice] = "Successfully added money to your account!"
        redirect_to user_path(@user)
      else
        flash[:alert] = "Please enter a valid amount"
        redirect_to addmoney_path
      end
    end

    def edit
      @user = User.find_by(id: session[:user_id])
    end

    def update
      @user = User.find_by(id: session[:user_id])
      @user.update(user_params)
      if @user.valid?
        flash[:notice] = "Your account was updated!"
        redirect_to user_path(@user)
      else
        flash[:alert] = @user.errors.full_messages
        redirect_to edit_user_path(@user)
      end
    end
     
    private
     
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password, :likes, :balance)
    end

    def require_login
      return head(:forbidden) unless session.include?(:user_id)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add.html.erb
<div class="container">
<h2>Current Balance: $<%= @user.display_balance %></h2>

<label>Please select a payment option:</label>
<select>
  <option value="visa">Visa</option>
  <option value="mastercard">MasterCard</option>
  <option value="amex">American Express</option>
  <option value="discover">Discover</option>
</select>
<br>

<label>Please enter the amount you would like to add to your account:</label><br>
<%= form_with scope: :user, url: user_path(@user) do |form| %>
    $<%= form.number_field :amount, step: "0.01" %><br>
    <%= form.submit "Submit" %>
<% end %>

<% if flash[:alert] %>
    <div class="alert text-danger"><%= flash[:alert] %></div>
<% end %>

</div>

app/views/users/edit.html.erb
<div class="container">
<%= form_for @user do |f| %>
  First Name: <%= f.text_field :first_name %><br>
  Last Name: <%= f.text_field :last_name %><br>
  Username: <%= f.text_field :username %><br>
  Password: <%= f.password_field :password %><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br>
  <%= f.hidden_field :likes, value: @user.likes %>
  <%= f.hidden_field :balance, value: @user.balance %>
  <%= f.submit "Submit" %>
<% end %>

<% if flash[:alert] %>
  <% flash[:alert].each do |alert| %>
    <div class="alert text-danger"><%= alert %></div>
  <% end %>
<% end %>

</div>

app/views/users/new.html.erb
<div class="container">
<%= form_for :user, url: users_path do |f| %>
  First Name: <%= f.text_field :first_name %><br>
  Last Name: <%= f.text_field :last_name %><br>
  Username: <%= f.text_field :username %><br>
  Password: <%= f.password_field :password %><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br>
  <%= f.hidden_field :likes, value: 0 %>
  <%= f.hidden_field :balance, value: 10.000 %>
  <%= f.submit "Submit" %>
<% end %>

<% if flash[:alert] %>
  <% flash[:alert].each do |alert| %>
    <div class="alert text-danger"><%= alert %></div>
  <% end %>
<% end %>

</div>

app/views/users/show.html.erb
<div class="container">

<div class="row">
    <div class="col-sm-6">
        <h1><%= @user.full_name %> <%= "(#{@user.approval_rating})" %></h1>
            <br>
        <h4>Username: <%= @user.username %></h4>
        <h4>Likes: <%= @user.display_likes %> </h4> 
        <h4>Total Exchanges: <%= @user.exchanges.size + @user.inactive_listings.size  %> </h4>
            <br>
        <h4> Balance: $<%= @user.display_balance %> </h4>
        <h5> <%= link_to "Add to Balance", addmoney_path %> </h5>
    </div>
    <div class="col-sm-6">
        <br>
        <img src="https://media.giphy.com/media/rPoYAKVYDhdh6/giphy.gif" class="img-responsive center-block" width="350px">
    </div>
</div>   
    <br><br>
<div class="row">
    <div class="col-sm-6">
        <h2>My Purchases:</h2>
        <% @user.exchanges.each do |exchange| %>
            <%= link_to exchange.display_purchase, exchange_path(exchange) %><br>
        <% end %>
    </div>
    <div class="col-sm-6">
        <h2>My Sales:</h2>
        <% @user.sales.each do |exchange| %>
            <%= link_to exchange.display_sale, exchange_path(exchange) %><br>
        <% end %>
    </div>
</div>
    <br><br>
<div class="row">
    <div class="col-sm-6">
        <h2>My Active Listings:</h2>
        <% @user.active_listings.each do |listing| %>
            <%= link_to "#{listing.product.name} created on #{listing.created_at.strftime("%b %e %Y")}", listing_path(listing) %><br>
        <% end %>
    </div>
    <div class="col-sm-6">
        <h2>My Closed Listings</h2>
        <% @user.inactive_listings.each do |listing| %>
            <%= link_to "#{listing.product.name} closed on #{listing.updated_at.strftime("%b %e %Y")}", listing_path(listing)%><br>
        <% end %>
    </div>

</div>

</div>