config/routes.rb
Rails.application.routes.draw do
  resources :exchanges, only: [:show, :create]
  get '/listings/new_road', to: 'listings#new_road', as: 'newroad'
  get '/listings/new_mountain', to: 'listings#new_mountain', as: 'newmountain'
  get '/listings/:id/edit_road', to: 'listings#edit_road', as: 'editroad'
  get '/listings/:id/edit_mountain', to: 'listings#edit_mountain', as: 'editmountain'
  post '/exchanges/:id', to: 'exchanges#add_like'
  resources :listings, only: [:create, :show, :update] do 
    resources :comments
  end
  resources :products, only: [:show] do
    resources :reviews
  end
  get '/', to: 'products#index', as: 'home'
  resources :users, only: [:new, :create, :show, :edit, :update]
  get '/users/:id/add', to: 'users#add', as: 'addmoney'
  post '/users/:id', to: 'users#add_money'
  post '/login', to: 'sessions#create'
  match '/logout', to: 'sessions#destroy', via: :delete
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :listing
  belongs_to :user, optional: true

  def display_timestamp
    self.created_at.strftime("posted on %a %b %e %Y at %l:%M %p")
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :listing
  belongs_to :user

  def buyer
    self.user
  end

  def seller
    self.listing.user
  end

  def buy
    buyer.balance = buyer.balance - self.listing.price
    buyer.save
  end

  def sell
    seller.balance = seller.balance + self.listing.price
    seller.save
  end

  def display_purchase
    "#{self.listing.product.name} purchased from #{self.seller.full_name} on #{self.created_at.strftime("%b %e %Y")}"
  end

  def display_sale
    "#{self.listing.product.name} sold to #{self.buyer.full_name} on #{self.created_at.strftime("%b %e %Y")}"
  end

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :product
  belongs_to :user, optional: true
  has_one :exchange
  has_many :comments

  validates :price, presence: true

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end

  def display_price
    '%.2f' % self.price
  end

end

app/models/product.rb
class Product < ApplicationRecord
  has_many :listings
  has_many :users, through: :listings
  has_many :reviews

  def active_listings
    self.listings.select {|listing| listing.active == true}
  end

  def inactive_listings
    self.listings.select {|listing| listing.active == false}
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  belongs_to :user, optional: true

  def display_timestamp
    self.created_at.strftime("posted on %a %b %e %Y at %l:%M %p")
  end
end

app/models/type.rb
class Type < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :listings
    has_many :products, through: :listings
    has_many :reviews
    has_many :comments
    has_many :exchanges
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :username, presence: true
    # validates :username, uniqueness: true
    validates :username, length: {minimum: 4}
    validates :balance, presence: true

    has_secure_password


    def full_name
        self.first_name + " " + self.last_name
    end

    def active_listings
        self.listings.select {|listing| listing.active == true}
    end

    def inactive_listings
        self.listings.select {|listing| listing.active == false}
    end

    def sales
        self.inactive_listings.map {|listing| listing.exchange}
    end

    def purchases
        self.exchanges
    end

    def total_purchases
        purchases.size
    end 

    def total_sales
        sales.size
    end

    def total_exchanges
        total_purchases + total_sales
    end

    def display_likes
        current_likes = self.likes
        myexchanges = self.exchanges.size + self.inactive_listings.size

        if current_likes >= myexchanges
            current_likes = myexchanges
            self.save
        else  
            current_likes = self.likes
        end
        current_likes
    end

    def approval_rating
        mylikes = self.display_likes.to_f
        myexchanges = self.exchanges.size.to_f + self.inactive_listings.size.to_f
        approvalpercent = ""

        if mylikes == 0 || myexchanges == 0 
            approvalpercent = "0%"
        else 
            approvalrating = (mylikes.to_f / myexchanges.to_f) * 100
            approvalpercent = "#{approvalrating.to_i}%"
        end
        approvalpercent
    end

    def display_balance
        '%.2f' % self.balance
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.listing_id = params[:listing_id]
      
        @comment.save
      
        redirect_to listing_path(@comment.listing)
    end

    private

    def comment_params
        params.require(:comment).permit(:listing_id, :user_id, :content)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
    def new_road
        @listing = Listing.new
    end

    def new_mountain
        @listing = Listing.new
    end

    def create
        @listing = Listing.create(listing_params)
        redirect_to listing_path(@listing)
    end

    def show
        @listing = Listing.find(params[:id])
        @comment = Comment.new
        @comment.listing_id = @listing.id
    end

    def edit_road
        @listing = Listing.find(params[:id])
    end

    def edit_mountain
        @listing = Listing.find(params[:id])
    end

    def update
        @listing = Listing.find(params[:id])
        @listing.update(listing_params)

        #send a flash notice on the page
        flash[:notice] = "Listing Updated!"

        redirect_to listing_path(@listing)
    end

    private

    def listing_params
        params.require(:listing).permit(:user_id, :product_id, :condition, :make, :size, :active, :price, :description)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @review = Review.new(review_params)
        @review.product_id = params[:product_id]
      
        @review.save
      
        redirect_to product_path(@review.product)
    end

    private

    def review_params
        params.require(:review).permit(:product_id, :user_id, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   before_action :require_login, only: [:show, :add, :edit]

    def new
    end

    def create
        @user = User.create(user_params)
        if @user.valid?
          flash[:notice] = "Created a new account!"
          redirect_to home_path
        else
          flash[:alert] = @user.errors.full_messages
          redirect_to new_user_path
        end
    end

    def show
      # @user = User.find(params[:id])
      @user = User.find_by(id: session[:user_id])
    end

    def add
      @user = User.find_by(id: session[:user_id])
    end

    def add_money
      @user = User.find_by(id: session[:user_id])

      if !params[:user][:amount].empty?
        @user.balance += params[:user][:amount].to_f
        @user.save
        flash[:notice] = "Successfully added money to your account!"
        redirect_to user_path(@user)
      else
        flash[:alert] = "Please enter a valid amount"
        redirect_to addmoney_path
      end
    end

    def edit
      @user = User.find_by(id: session[:user_id])
    end

    def update
      @user = User.find_by(id: session[:user_id])
      @user.update(user_params)
      if @user.valid?
        flash[:notice] = "Your account was updated!"
        redirect_to user_path(@user)
      else
        flash[:alert] = @user.errors.full_messages
        redirect_to edit_user_path(@user)
      end
    end
     
    private
     
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :password, :likes, :balance)
    end

    def require_login
      return head(:forbidden) unless session.include?(:user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>iBikeapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <!-- Bootstrap CSS -->
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>


<div class="container">

  <nav class="navbar navbar-dark bg-secondary">
    <a class="navbar-brand" href=<%= home_path %>>iBike</a>

      <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
      <% elsif flash[:error] %>
        <div class="error text-danger"><%= flash[:error] %></div>
      <% end %>


      <% if !logged_in? %>
        <%= render '/sessions/form'%>

      <ul class="navbar-nav navbar-right">
        <li class="nav-item active">
          <a class="nav-link" href=<%= new_user_path %>>Register</a>
        </li>
      </ul>

      <% else %>
      <a href="<%= newmountain_path %>"> Create a MTB listing<span class="caret"></span></a> 
      <a href="<%= newroad_path %>"> Create a Road Listing<span class="caret"></span></a> 
      <a href="<%= user_path(current_user.id) %>" > View Profile<span class="caret"></span></a> 
      <a href="<%= edit_user_path(current_user.id) %>" > Edit Profile<span class="caret"></span></a> 
      <a href=<%= logout_path %> data-method="delete"%>Logout</a>

      
      <% end %>
  </nav>
</div>

  <body>
    <%= yield %>
  </body>
</html>